# Generated by Django 5.2.14 on 2026-05-26 20:24
""" Initial migration for the Word model. """

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "normalized_text",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["normalized_text"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(weight__gte=0),
                        name="corpus_word_weight_nonnegative",
                    )
                ],
            },
        ),
    ]
