# Generated by Django 5.2.14 on 2026-06-02 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="weight",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2147483647),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="word",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__lte", 2147483647)),
                name="corpus_word_weight_lte_max",
            ),
        ),
    ]
